version: '3.7'

services:
  selenium-hub:
   image: selenium/hub:4.0.0-alpha-6-20200730
   ports:
     - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  opera:
    image: selenium/node-opera:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'