drop table if exists lance CASCADE
drop table if exists leilao CASCADE
drop table if exists userss		 CASCADE 

create table lance (id bigint generated by default as identity, data date not null, valor decimal(19,2) not null, leilao_id bigint not null, usuario_user_id bigint, primary key (id))
create table leilao (id bigint generated by default as identity, data_abertura date not null, nome varchar(255) not null, usado boolean not null, valor_inicial decimal(19,2) not null, usuario_user_id bigint not null, primary key (id))
create table users (user_id bigint generated by default as identity, email varchar(255) not null, enabled boolean not null, username varchar(255) not null, role varchar(255), password varchar(255) not null, primary key (user_id))

alter table lance add constraint FKao15gcf542nf81fp2qq5j3igu foreign key (leilao_id) references leilao
alter table lance add constraint FKa0r0xo76a1ld305ao4kweawcb foreign key (usuario_user_id) references users
alter table leilao add constraint FKja7vplfvv740bo6vccdmgg3ne foreign key (usuario_user_id) references users
